### ISSUE TITLE
Euro Currency and Crash Resolve

### ISSUE THREAD

**Issue by hackaros** [Laaen/MizipTools#15]
Could you add the currency in Euros (€)?  Other than that, I believe the crash is due to the fact that the app should have permission to access the phone's files.  Sorry for writing here but I don't know how to write to you privately.

**Comment by e11storty** [comment]
what i can do of my app keep crashing?

**Comment by Laaen** [comment]
@hackaros Hello ! 
Sorry for the delay.
I changed the currency to be by default in euros, but it really doesn't change anything. When you use the app' there is no conversions or stuff like that, you can manipulate your tag's ammount of money without caring about which currency is displayed by the app.

The crash on file access is also fixed, thanks for the insight ;)

I'll build and release the fixed version later today.

@e11storty Hello !
I'll need more informations about the repeating crashes.
Do they happen when you try to start it ? If so, make sure NFC is enabled on your phone, and if NFC is enabled, please tell me the model of your phone.
If it crashes when using it, tell me what functionnality were you using when it crashed (dump, write, erase, ...)
